host: 127.0.0.1
port: 8088
server: http://110.42.96.40:9999

theme: default

globalVariables:
  defaultLanguage: en
  supportLanguages: # use value in i18n.js
    - en
    - zh-hans
    - ko-kr
    - tr-tr
    - ru
